wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1635676391
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      4: 3.8.10
      5: 0.12.6
      8:
      - 1
      - 5
